name: python-machine-learning-book-2nd-edition
dependencies:
- python=3.6
- numpy
- scikit-learn
- pandas
- matplotlib
- jupyter
- cython
<<<<<<< HEAD
- nltk
=======
- flask
- wtforms
>>>>>>> 19cd9d4197c0a452f69247874eadcb08dfb81da1
- pip:
  - tensorflow
  - watermark  
  - pyprind
