name: python-machine-learning-book-2nd-edition
dependencies:
- python=3.6
- numpy
- scikit-learn
- pandas
- matplotlib
- jupyter
- cython
- nltk
- flask
- wtforms
- seaborn
- pip:
  - tensorflow
  - watermark  
  - pyprind
